# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/LeptonModule/software/LeptonSDKEmb32PUB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/LeptonModule/software/LeptonSDKEmb32PUB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/LeptonModule/software/LeptonSDKEmb32PUB/CMakeFiles /home/pi/LeptonModule/software/LeptonSDKEmb32PUB/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/LeptonModule/software/LeptonSDKEmb32PUB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LeptonSDK

# Build rule for target.
LeptonSDK: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LeptonSDK
.PHONY : LeptonSDK

# fast build rule for target.
LeptonSDK/fast:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/build
.PHONY : LeptonSDK/fast

CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.o: CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.o

.PHONY : CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.o

# target to build an object file
CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.o
.PHONY : CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.o

CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.i: CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.i

.PHONY : CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.i

# target to preprocess a source file
CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.i
.PHONY : CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.i

CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.s: CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.s

.PHONY : CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.s
.PHONY : CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c.s

LEPTON_AGC.o: LEPTON_AGC.c.o

.PHONY : LEPTON_AGC.o

# target to build an object file
LEPTON_AGC.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_AGC.c.o
.PHONY : LEPTON_AGC.c.o

LEPTON_AGC.i: LEPTON_AGC.c.i

.PHONY : LEPTON_AGC.i

# target to preprocess a source file
LEPTON_AGC.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_AGC.c.i
.PHONY : LEPTON_AGC.c.i

LEPTON_AGC.s: LEPTON_AGC.c.s

.PHONY : LEPTON_AGC.s

# target to generate assembly for a file
LEPTON_AGC.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_AGC.c.s
.PHONY : LEPTON_AGC.c.s

LEPTON_I2C_Protocol.o: LEPTON_I2C_Protocol.c.o

.PHONY : LEPTON_I2C_Protocol.o

# target to build an object file
LEPTON_I2C_Protocol.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_I2C_Protocol.c.o
.PHONY : LEPTON_I2C_Protocol.c.o

LEPTON_I2C_Protocol.i: LEPTON_I2C_Protocol.c.i

.PHONY : LEPTON_I2C_Protocol.i

# target to preprocess a source file
LEPTON_I2C_Protocol.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_I2C_Protocol.c.i
.PHONY : LEPTON_I2C_Protocol.c.i

LEPTON_I2C_Protocol.s: LEPTON_I2C_Protocol.c.s

.PHONY : LEPTON_I2C_Protocol.s

# target to generate assembly for a file
LEPTON_I2C_Protocol.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_I2C_Protocol.c.s
.PHONY : LEPTON_I2C_Protocol.c.s

LEPTON_I2C_Service.o: LEPTON_I2C_Service.c.o

.PHONY : LEPTON_I2C_Service.o

# target to build an object file
LEPTON_I2C_Service.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_I2C_Service.c.o
.PHONY : LEPTON_I2C_Service.c.o

LEPTON_I2C_Service.i: LEPTON_I2C_Service.c.i

.PHONY : LEPTON_I2C_Service.i

# target to preprocess a source file
LEPTON_I2C_Service.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_I2C_Service.c.i
.PHONY : LEPTON_I2C_Service.c.i

LEPTON_I2C_Service.s: LEPTON_I2C_Service.c.s

.PHONY : LEPTON_I2C_Service.s

# target to generate assembly for a file
LEPTON_I2C_Service.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_I2C_Service.c.s
.PHONY : LEPTON_I2C_Service.c.s

LEPTON_OEM.o: LEPTON_OEM.c.o

.PHONY : LEPTON_OEM.o

# target to build an object file
LEPTON_OEM.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_OEM.c.o
.PHONY : LEPTON_OEM.c.o

LEPTON_OEM.i: LEPTON_OEM.c.i

.PHONY : LEPTON_OEM.i

# target to preprocess a source file
LEPTON_OEM.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_OEM.c.i
.PHONY : LEPTON_OEM.c.i

LEPTON_OEM.s: LEPTON_OEM.c.s

.PHONY : LEPTON_OEM.s

# target to generate assembly for a file
LEPTON_OEM.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_OEM.c.s
.PHONY : LEPTON_OEM.c.s

LEPTON_SDK.o: LEPTON_SDK.c.o

.PHONY : LEPTON_SDK.o

# target to build an object file
LEPTON_SDK.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_SDK.c.o
.PHONY : LEPTON_SDK.c.o

LEPTON_SDK.i: LEPTON_SDK.c.i

.PHONY : LEPTON_SDK.i

# target to preprocess a source file
LEPTON_SDK.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_SDK.c.i
.PHONY : LEPTON_SDK.c.i

LEPTON_SDK.s: LEPTON_SDK.c.s

.PHONY : LEPTON_SDK.s

# target to generate assembly for a file
LEPTON_SDK.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_SDK.c.s
.PHONY : LEPTON_SDK.c.s

LEPTON_SYS.o: LEPTON_SYS.c.o

.PHONY : LEPTON_SYS.o

# target to build an object file
LEPTON_SYS.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_SYS.c.o
.PHONY : LEPTON_SYS.c.o

LEPTON_SYS.i: LEPTON_SYS.c.i

.PHONY : LEPTON_SYS.i

# target to preprocess a source file
LEPTON_SYS.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_SYS.c.i
.PHONY : LEPTON_SYS.c.i

LEPTON_SYS.s: LEPTON_SYS.c.s

.PHONY : LEPTON_SYS.s

# target to generate assembly for a file
LEPTON_SYS.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_SYS.c.s
.PHONY : LEPTON_SYS.c.s

LEPTON_VID.o: LEPTON_VID.c.o

.PHONY : LEPTON_VID.o

# target to build an object file
LEPTON_VID.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_VID.c.o
.PHONY : LEPTON_VID.c.o

LEPTON_VID.i: LEPTON_VID.c.i

.PHONY : LEPTON_VID.i

# target to preprocess a source file
LEPTON_VID.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_VID.c.i
.PHONY : LEPTON_VID.c.i

LEPTON_VID.s: LEPTON_VID.c.s

.PHONY : LEPTON_VID.s

# target to generate assembly for a file
LEPTON_VID.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/LEPTON_VID.c.s
.PHONY : LEPTON_VID.c.s

crc16fast.o: crc16fast.c.o

.PHONY : crc16fast.o

# target to build an object file
crc16fast.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/crc16fast.c.o
.PHONY : crc16fast.c.o

crc16fast.i: crc16fast.c.i

.PHONY : crc16fast.i

# target to preprocess a source file
crc16fast.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/crc16fast.c.i
.PHONY : crc16fast.c.i

crc16fast.s: crc16fast.c.s

.PHONY : crc16fast.s

# target to generate assembly for a file
crc16fast.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/crc16fast.c.s
.PHONY : crc16fast.c.s

raspi_I2C.o: raspi_I2C.c.o

.PHONY : raspi_I2C.o

# target to build an object file
raspi_I2C.c.o:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/raspi_I2C.c.o
.PHONY : raspi_I2C.c.o

raspi_I2C.i: raspi_I2C.c.i

.PHONY : raspi_I2C.i

# target to preprocess a source file
raspi_I2C.c.i:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/raspi_I2C.c.i
.PHONY : raspi_I2C.c.i

raspi_I2C.s: raspi_I2C.c.s

.PHONY : raspi_I2C.s

# target to generate assembly for a file
raspi_I2C.c.s:
	$(MAKE) -f CMakeFiles/LeptonSDK.dir/build.make CMakeFiles/LeptonSDK.dir/raspi_I2C.c.s
.PHONY : raspi_I2C.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... LeptonSDK"
	@echo "... edit_cache"
	@echo "... CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.o"
	@echo "... CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.i"
	@echo "... CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.s"
	@echo "... LEPTON_AGC.o"
	@echo "... LEPTON_AGC.i"
	@echo "... LEPTON_AGC.s"
	@echo "... LEPTON_I2C_Protocol.o"
	@echo "... LEPTON_I2C_Protocol.i"
	@echo "... LEPTON_I2C_Protocol.s"
	@echo "... LEPTON_I2C_Service.o"
	@echo "... LEPTON_I2C_Service.i"
	@echo "... LEPTON_I2C_Service.s"
	@echo "... LEPTON_OEM.o"
	@echo "... LEPTON_OEM.i"
	@echo "... LEPTON_OEM.s"
	@echo "... LEPTON_SDK.o"
	@echo "... LEPTON_SDK.i"
	@echo "... LEPTON_SDK.s"
	@echo "... LEPTON_SYS.o"
	@echo "... LEPTON_SYS.i"
	@echo "... LEPTON_SYS.s"
	@echo "... LEPTON_VID.o"
	@echo "... LEPTON_VID.i"
	@echo "... LEPTON_VID.s"
	@echo "... crc16fast.o"
	@echo "... crc16fast.i"
	@echo "... crc16fast.s"
	@echo "... raspi_I2C.o"
	@echo "... raspi_I2C.i"
	@echo "... raspi_I2C.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

